version: '3.8'

services:
  regen-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regen-node1
    environment:
      - NODE_NAME=regen-node1
      - REGEN_NODE1_VALIDATOR_ADDRESS=${REGEN_NODE1_VALIDATOR_ADDRESS}
      - REGEN_NODE1_VALIDATOR_MNEMONIC=${REGEN_NODE1_VALIDATOR_MNEMONIC}
      - REGEN_NODE2_VALIDATOR_ADDRESS=${REGEN_NODE2_VALIDATOR_ADDRESS}
      - REGEN_NODE2_VALIDATOR_MNEMONIC=${REGEN_NODE2_VALIDATOR_MNEMONIC}
      - REGEN_NODE3_VALIDATOR_ADDRESS=${REGEN_NODE3_VALIDATOR_ADDRESS}
      - REGEN_NODE3_VALIDATOR_MNEMONIC=${REGEN_NODE3_VALIDATOR_MNEMONIC}
    volumes:
      - ./shared:/mnt/nvme/shared
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "26656:26656"  # P2P Port
      - "26657:26657"  # RPC Port
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    networks:
      - regen-network

  regen-node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regen-node2
    environment:
      - NODE_NAME=regen-node2
      - REGEN_NODE1_VALIDATOR_ADDRESS=${REGEN_NODE1_VALIDATOR_ADDRESS}
      - REGEN_NODE1_VALIDATOR_MNEMONIC=${REGEN_NODE1_VALIDATOR_MNEMONIC}
      - REGEN_NODE2_VALIDATOR_ADDRESS=${REGEN_NODE2_VALIDATOR_ADDRESS}
      - REGEN_NODE2_VALIDATOR_MNEMONIC=${REGEN_NODE2_VALIDATOR_MNEMONIC}
      - REGEN_NODE3_VALIDATOR_ADDRESS=${REGEN_NODE3_VALIDATOR_ADDRESS}
      - REGEN_NODE3_VALIDATOR_MNEMONIC=${REGEN_NODE3_VALIDATOR_MNEMONIC}
    volumes:
      - ./shared:/mnt/nvme/shared
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "26658:26656"  # P2P Port
      - "26659:26657"  # RPC Port
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    networks:
      - regen-network

  regen-node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regen-node3
    environment:
      - NODE_NAME=regen-node3
      - REGEN_NODE1_VALIDATOR_ADDRESS=${REGEN_NODE1_VALIDATOR_ADDRESS}
      - REGEN_NODE1_VALIDATOR_MNEMONIC=${REGEN_NODE1_VALIDATOR_MNEMONIC}
      - REGEN_NODE2_VALIDATOR_ADDRESS=${REGEN_NODE2_VALIDATOR_ADDRESS}
      - REGEN_NODE2_VALIDATOR_MNEMONIC=${REGEN_NODE2_VALIDATOR_MNEMONIC}
      - REGEN_NODE3_VALIDATOR_ADDRESS=${REGEN_NODE3_VALIDATOR_ADDRESS}
      - REGEN_NODE3_VALIDATOR_MNEMONIC=${REGEN_NODE3_VALIDATOR_MNEMONIC}
    volumes:
      - ./shared:/mnt/nvme/shared
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "26660:26656"  # P2P Port
      - "26661:26657"  # RPC Port
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    networks:
      - regen-network

networks:
  regen-network:
    driver: bridge
